name: CI

on:
  push:
    branches: [main]
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2.0.1
        name: Install pnpm
        with:
          run_install: true
          version: 7
      
      - name: Check linting
        run: pnpm lint
      
      - name: Build typescript
        run: pnpm tsc
      
      - name: Remove dist folder
        run: rm -rf ./dist
      
      - name: Test
        run: pnpm run test --coverage --detectOpenHandles --forceExit
